on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COMPOSE_RUNNER: "docker compose"
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('compose.yaml') }}

      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git permissions
        run: git config --global --add safe.directory /__w/serendipity/serendipity

      - name: Put everything up
        run: make setup

      - name: Run tests and generate coverage
        run: make ci

      - name: Run SonarCloud analysis
        run: make sonar
